apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-eraser
  namespace: projects
  labels:
    app: bg-eraser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bg-eraser
  template:
    metadata:
      labels:
        app: bg-eraser
    spec:
      containers:
        - name: bg-eraser
          image: localhost:32000/projects/bg-eraser:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: '0.25'
          env:
            - name: BASE_URL
              value: https://bg-eraser.com
