apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bg-eraser
  namespace: projects
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: dns01
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bg-eraser.com
      secretName: bg-eraser-com-cert
  rules:
    - host: bg-eraser.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: bg-eraser
                port:
                  number: 3000
